Feat/order dialog
librocco/librocco pull request #390
Opened 2024-02-02 12:33 UTC by delasous

Closes T-328

I simplified the design of the order confirmation dialog to bring it in line with the existing dialog. This PR just makes a few small tweaks to the existing component setup/use and adds a story.

2024-02-06 09:06 UTC, ikusteu commented on pkg/shared/package.json
> +			}
👌

2024-02-06 09:07 UTC, ikusteu submitted a review, later dismissed
LGTM

2024-02-06 09:22 UTC, ikusteu requested changes
Committing an inbound note, I get this in the dialog (same happens for an outbound note):
<img width="1512" alt="Screenshot 2024-02-06 at 10 15 43" src="https://github.com/librocco/librocco/assets/72689023/9d085c9a-48ec-4fad-a67a-23bee047d3f9">

Editing the warehouse: 
- clicking 'Save' works as expected
- clicking 'Cancel' acts the same way as 'Save' (updates are applied and changes stored to the db)

2024-02-09 12:11 UTC, delasous commented
@ikusteu I fixed the title and description issue, but I'm not seeing the "Cancel submit" behaviour that you're describing. Can you confirm if it's still there?

2024-02-13 19:04 UTC, merged