Enhancement/customer order UI
librocco/librocco pull request #560
Opened 2024-10-28 19:43 UTC by fadwamahmoud

2024-10-31 05:09 UTC, delasous approved these changes

2024-10-31 05:09 UTC, delasous commented on apps/web-client/src/lib/components/TextEditable/NumberEditable.svelte
I think it would be better to pass the input as a slot in order to switch between text and number. The classes defind on the input can be passed as a slot prop and applied when the slot content is passed

2024-11-04 14:09 UTC, silviot requested changes
I tried [the deployed app](https://test.libroc.co/enhancement/customerOrder_UI/customers/) and I was not able to edit customer details.

I also think the PR needs a description briefly mentioning what changes are in the PR and why they improve on the status quo.

2024-11-04 16:19 UTC, fadwamahmoud commented
> I tried [the deployed app](https://test.libroc.co/enhancement/customerOrder_UI/customers/) and I was not able to edit customer details.
> 
> I also think the PR needs a description briefly mentioning what changes are in the PR and why they improve on the status quo.

Fixed it. The input field values were not propagating back to the customer store

2024-11-05 15:58 UTC, silviot approved these changes

2024-11-05 15:58 UTC, merged