Feature/supplier order view
librocco/librocco pull request #648
Opened 2024-12-21 22:34 UTC by fadwamahmoud

Create supplier order details view

2024-12-23 15:58 UTC, silviot commented
I need to be able to view the view here. As soon as #597 goes in I will be able to and will review.

2025-01-01 06:30 UTC, delasous requested changes

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/components/supplier-orders/OrderedTable.svelte
> +					<td class="flex items-center justify-evenly text-right">
The table needs an extra `<td scope="col">`  in the table head

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/db/cr-sqlite/__tests__/supplier-order.test.ts
> +				total_price: 37,
If this is the "total_book_number" and "total_price" for all lines in this placed supplier order, I'm not sure it makes sense returning it per row in the result?  Similar with "supplier_id", "supplier_name", "supplier_order_id"?

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/db/cr-sqlite/suppliers.ts
> +	LEFT JOIN supplier_order so ON so.id = sol.supplier_order_id
Is LEFT JOIN necessary on "supplier_order" and "supplier"?

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/db/cr-sqlite/types.ts
> +export type SupplierPlacedOrderLine = {
This type looks more like the data for a supplier order, not a line?

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/paths.ts
> +	supplier_order_status: `${basepath}/orders/suppliers/order/`,
I'm not convinced by these routes, but I don't think we should worry too much about it here. Just leaving a note that I will write up a ticket for discussion

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.svelte
> +			<div class="card fixed bottom-4 left-0 z-10 flex w-screen flex-row bg-transparent md:absolute md:bottom-24 md:mx-2 md:w-full">
I don't think this bar needs to be here on this view. It's meant to pop up to show a summary before allowing the user to place the order

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.svelte
> +								<dt class="stat-title">Last updated</dt>
Change to "Ordered"

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.svelte
> +					<button class="btn-primary btn" on:click={handlePrintOrder}>
Move this below the order summary in the left bar. See the customer order view

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.svelte
> +	import { createSupplierOrder } from "$lib/db/cr-sqlite/suppliers";
Remove unused imports

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.ts
> +	console.log({ placedOrder });
Remove

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.ts
> +	// const placedOrder = placedOrders?.find((order) => order.id === parseInt(params.id));
Remove

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/routes/orders/suppliers/order/[id]/+page.ts
> +	// const placedOrder = placedOrders?.find((order) => order.id === parseInt(params.id));
Add/use a separate query to get a placed supplier order meta data. We could potentially add an optional supplierId param to `getPlacedSupplierOrders`?

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/db/cr-sqlite/suppliers.ts
> + * @param supplier - The supplier data1 to upsert
typo

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/db/cr-sqlite/suppliers.ts
> +export async function getPlacedSupplierOrderLines(db: DB, supplier_order_id: number): Promise<(SupplierPlacedOrderLine & BookEntry)[]> {
Add JSDOC comment

2025-01-01 06:30 UTC, delasous commented on apps/web-client/src/lib/db/cr-sqlite/__tests__/supplier-order.test.ts
> +	it("should order results consistently", async () => {
I don't see anything in the query that orders?

2025-01-12 16:09 UTC, fadwamahmoud commented on apps/web-client/src/lib/db/cr-sqlite/__tests__/supplier-order.test.ts
> +				total_price: 37,
I was thinking the less queries the better and the placed order meta data was easy to include with this query

2025-01-12 16:10 UTC, fadwamahmoud commented on apps/web-client/src/lib/components/supplier-orders/OrderedTable.svelte
> +					<td class="flex items-center justify-evenly text-right">
I can't quite place where this is missing..

2025-01-12 16:19 UTC, fadwamahmoud commented on apps/web-client/src/lib/db/cr-sqlite/__tests__/supplier-order.test.ts
> +	it("should order results consistently", async () => {
right...aider suggested to include it and I went along

2025-01-13 05:59 UTC, delasous commented on apps/web-client/src/lib/components/supplier-orders/OrderedTable.svelte
> +					<td class="flex items-center justify-evenly text-right">
In `thead`

2025-01-13 16:38 UTC, merged